{
    "name": "Webhooks Framework - Outbound Delivery",
    "version": "18.0.1.1.0",
    "category": "Tools",
    "summary": "Reliable outbound webhook delivery with templated requests and robust retries.",
    "development_status": "Production",
    "depends": ["bwt_webhooks_core"],
    "data": [
        "security/ir.model.access.csv",
        "security/webhook_security.xml",
        "data/queue_job_function_data.xml",
        "views/webhook_outbound_endpoint_views.xml",
        "views/webhook_handler_views.xml",
        "views/webhook_outbound_delivery_views.xml",
        "views/webhook_menu_views.xml",
    ],
    "demo": [
        "demo/webhook_demo_endpoint_loopback.xml",
        "demo/webhook_demo_rules_outbound.xml",
        "demo/webhook_demo_delivery_context.xml",
    ],
    "author": "Bitwise Technologies LLC",
    "contributors": ["Youssef Egla"],
    "license": "OPL-1",
    "price": 0.0,
    "currency": "USD",
    "images": ["static/description/banner.png", "static/description/icon.png"],
    "installable": True,
}
