name: tests

on:
  pull_request:
    branches:
      - main
      - "19.0*"
  push:
    branches:
      - main
      - "19.0*"

jobs:
  unreleased-deps:
    runs-on: ubuntu-latest
    name: Detect unreleased dependencies
    steps:
      - uses: actions/checkout@v4
      - run: |
          for reqfile in requirements.txt test-requirements.txt ; do
              if [ -f ${reqfile} ] ; then
                  result=0
                  grep "^[^#].*/" ${reqfile} || result=$?
                  if [ $result -eq 0 ] ; then
                      echo "Unreleased dependencies found in ${reqfile}."
                      exit 1
                  fi
              fi
          done

  test:
    runs-on: ubuntu-22.04
    container: ${{ matrix.container }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: ghcr.io/oca/oca-ci/py3.10-odoo19.0:latest
            name: test with Odoo
            makepot: "true"
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    env:
      OCA_ENABLE_CHECKLOG_ODOO: "1"
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Checkout queue fork
        uses: actions/checkout@v4
        with:
          repository: bitwise-hq/odoo-oca-queue
          ref: "19.0"
          path: deps/odoo-oca-queue
          fetch-depth: 1
          sparse-checkout: |
            queue_job
          sparse-checkout-cone-mode: true
          persist-credentials: false
      - name: Checkout connector fork
        uses: actions/checkout@v4
        with:
          repository: bitwise-hq/odoo-oca-connector
          ref: "19.0"
          path: deps/odoo-oca-connector
          fetch-depth: 1
          sparse-checkout: |
            component
            component_event
            connector
          sparse-checkout-cone-mode: true
          persist-credentials: false
      - name: Configure external addon paths
        run: |
          echo "ADDONS_PATH=$ADDONS_PATH,$PWD/deps/odoo-oca-queue,$PWD/deps/odoo-oca-connector" >> $GITHUB_ENV
      - name: Preinstall unreleased addon dependencies
        run: |
          git config --global --add safe.directory $PWD/deps/odoo-oca-queue
          git config --global --add safe.directory $PWD/deps/odoo-oca-connector
          python -m pip install cachetools
      - name: Install addons and dependencies
        run: oca_install_addons
      - name: Check licenses
        run: manifestoo -d . check-licenses
      - name: Check development status
        run: manifestoo -d . check-dev-status --default-dev-status=Beta
      - name: Initialize test db
        run: oca_init_test_database
      - name: Run tests
        run: oca_run_tests
      - uses: codecov/codecov-action@v4
        if: ${{ env.CODECOV_TOKEN != '' }}
        with:
          slug: ${{ github.repository }}
          token: ${{ env.CODECOV_TOKEN }}
      - name: Update .pot files
        run: oca_export_and_push_pot https://x-access-token:${{ secrets.GIT_PUSH_TOKEN }}@github.com/${{ github.repository }}
        if: ${{ matrix.makepot == 'true' && github.event_name == 'push' && github.repository_owner == 'OCA' }}